# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

#

Import('gateway_env')

gwcnc_env = gateway_env.Clone()

if gwcnc_env['BR'] == 'on':
    gwcnc_env['BR'] = 'off'

gwcnc_env.Append(CPPPATH = '$DISTDIR/common/inc')
gwcnc_env.Prepend(LIBS = ['alljoyn_about', 'alljoyn_services_common', 'alljoyn_gwcommon', 'alljoyn_notification', 'alljoyn_config', 'alljoyn_gwconnector'])

srcs = gwcnc_env.Glob('*.cc')
objs = gwcnc_env.Object(srcs)

prog = gwcnc_env.Program('alljoyn-gwconnectorsample', objs)

# Prepare for building tar
gwcnc_env.Install('$GWCNC_DISTDIR/tar', gwcnc_env.Glob('Manifest.xml'))
gwcnc_env.Install('$GWCNC_DISTDIR/tar/bin', prog)
gwcnc_env.Install('$GWCNC_DISTDIR/tar/bin', gwcnc_env.Glob('postTweet.sh'))
gwcnc_env.Install('$GWCNC_DISTDIR/tar/bin', gwcnc_env.Glob('directMessage.sh'))

if gwcnc_env['OS'] == 'linux':
    gwcnc_env.Install('$GWCNC_DISTDIR/tar/lib', gwcnc_env.Glob('$GWCNC_DISTDIR/lib/*.so'))
    gwcnc_env.Install('$GWCNC_DISTDIR/tar/lib', gwcnc_env.Glob('$DISTDIR/cpp/lib/*.so'))
    gwcnc_env.Install('$GWCNC_DISTDIR/tar/lib', gwcnc_env.Glob('$DISTDIR/about/lib/*.so'))
    gwcnc_env.Install('$GWCNC_DISTDIR/tar/lib', gwcnc_env.Glob('$DISTDIR/services_common/lib/*'))
    gwcnc_env.Install('$GWCNC_DISTDIR/tar/lib', gwcnc_env.Glob('$DISTDIR/notification/lib/*'))
    gwcnc_env.Install('$GWCNC_DISTDIR/tar/lib', gwcnc_env.Glob('$DISTDIR/config/lib/*.so'))

Return('prog')