# Copyright (c) 2013, AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Import('gateway_env')
import os

#build command line option --pmcl indicates build the PM command line app (see \gwagent\SConstruct).
excluded = 'pmcl.cc'
programName = 'PackageManagerGtest'
if GetOption('pmcl') : 
    excluded = 'pmgtest.cc' 	
    programName = 'PackageManagerCL'

srcs = gateway_env.Object([f for f in Glob('*.cc')
    if excluded not in f.path])
    
print 'building PM version ' + programName	

gateway_env.Append(LIBPATH =['/usr/lib'])
gateway_env.Append(LIBS = ['curl'])
if not GetOption('pmcl') :
    gateway_env.Append(LIBS = ['gtest'])
    gateway_env.Append(LIBS = ['gtest_main'])

prog = gateway_env.Program(programName, srcs )
Return('prog')
